Repository NRLMMD-GEOIPS/geoips, pull requests merged in 2023-09, with the labels that each got.

#314 Add reader_kwargs command line option
  docs/source/releases/v1_11_3a0.rst
  geoips/commandline/args.py
  geoips/plugins/modules/procflows/config_based.py
  geoips/plugins/modules/procflows/single_source.py
  geoips/plugins/modules/readers/ahi_hsd.py
  geoips/plugins/modules/readers/amsr2_netcdf.py
  tests/scripts/amsr2.config_based_no_compare.sh
  tests/scripts/amsr2.tc.89H-Physical.imagery_annotated.sh
  tests/yaml_configs/amsr2_test_low_memory.yaml
Labels: bug

#320 286 empty plugin raises unhelpful error
  docs/source/releases/v1_11_3a0.rst
  geoips/geoips_utils.py
Labels: bug

#319 287 reevaluate geoips print statements
  docs/source/releases/v1_11_3a0.rst
  geoips/cli.py
  geoips/commandline/args.py
  geoips/commandline/create_sector_image.py
  geoips/commandline/list_available_modules.py
  geoips/commandline/list_available_plugins.py
  geoips/commandline/test_interfaces.py
  geoips/image_utils/maps.py
  geoips/plugins/modules/colormappers/visir/IR_BD.py
  geoips/plugins/modules/colormappers/visir/WV.py
  geoips/plugins/modules/filename_formatters/geoips_fname.py
  geoips/plugins/modules/filename_formatters/tc_fname.py
  geoips/plugins/modules/procflows/single_source.py
  geoips/plugins/modules/readers/abi_netcdf.py
  geoips/plugins/modules/readers/ahi_hsd.py
  geoips/plugins/modules/readers/amsub_hdf.py
  geoips/plugins/modules/readers/amsub_mirs.py
  geoips/plugins/modules/readers/ewsg_netcdf.py
  geoips/plugins/modules/readers/modis_hdf4.py
  geoips/plugins/modules/readers/seviri_hrit.py
  geoips/plugins/modules/readers/ssmi_binary.py
  geoips/plugins/modules/readers/utils/geostationary_geolocation.py
  geoips/plugins/modules/readers/viirs_netcdf.py
  geoips/plugins/modules/readers/windsat_idr37_binary.py
  geoips/sector_utils/estimate_area_extent.py
  geoips/sector_utils/overpass_predictor.py
  geoips/utils/memusg.py
  pyproject.toml
  tests/integration_tests/full_test.sh
  tests/scripts/console_script_create_sector_image.sh
  tests/scripts/console_script_list_available_plugins.sh
Labels: refactor

#340 Remove imagemagick requirement
  docs/source/releases/v1_11_3a0.rst
  docs/source/starter/installation.rst
  geoips/compare_outputs.py
Labels: installation

#349 Create default v1_11_5a0.rst in geoips repo
  docs/source/releases/v1_11_5a0.rst
Labels: actions

#350 Fix Flake8 Errors
  docs/source/_templates/conf_PKG.py
  docs/source/releases/index.rst
  docs/source/releases/v1_11_5a0.rst
  geoips/commandline/args.py
  geoips/image_utils/maps.py
  geoips/interfaces/module_based/filename_formatters.py
  geoips/interfaces/yaml_based/sectors.py
  geoips/plugins/modules/interpolators/utils/boxdefinitions.py
  geoips/plugins/modules/output_formatters/full_disk_image.py
  geoips/plugins/modules/output_formatters/metadata_tc.py
  geoips/plugins/modules/procflows/config_based.py
  geoips/plugins/modules/procflows/single_source.py
  geoips/plugins/modules/readers/abi_netcdf.py
  geoips/plugins/modules/readers/ahi_hsd.py
  geoips/plugins/modules/readers/amsr2_netcdf.py
  geoips/plugins/modules/readers/amsr2_remss_winds_netcdf.py
  geoips/plugins/modules/readers/amsub_hdf.py
  geoips/plugins/modules/readers/amsub_mirs.py
  geoips/plugins/modules/readers/ascat_uhr_netcdf.py
  geoips/plugins/modules/readers/ewsg_netcdf.py
  geoips/plugins/modules/readers/gmi_hdf5.py
  geoips/plugins/modules/readers/imerg_hdf5.py
  geoips/plugins/modules/readers/modis_hdf4.py
  geoips/plugins/modules/readers/saphir_hdf5.py
  geoips/plugins/modules/readers/sar_winds_netcdf.py
  geoips/plugins/modules/readers/scat_knmi_winds_netcdf.py
  geoips/plugins/modules/readers/scat_noaa_winds_netcdf.py
  geoips/plugins/modules/readers/seviri_hrit.py
  geoips/plugins/modules/readers/smap_remss_winds_netcdf.py
  geoips/plugins/modules/readers/smos_winds_netcdf.py
  geoips/plugins/modules/readers/ssmi_binary.py
  geoips/plugins/modules/readers/ssmis_binary.py
  geoips/plugins/modules/readers/utils/geostationary_geolocation.py
  geoips/plugins/modules/readers/utils/hrit_reader.py
  geoips/plugins/modules/readers/viirs_netcdf.py
  geoips/plugins/modules/readers/windsat_idr37_binary.py
  geoips/plugins/modules/readers/windsat_remss_winds_netcdf.py
  geoips/plugins/modules/title_formatters/static_standard.py
  geoips/plugins/modules/title_formatters/tc_copyright.py
  geoips/plugins/modules/title_formatters/tc_standard.py
  geoips/sector_utils/estimate_area_extent.py
  geoips/sector_utils/overpass_predictor.py
  geoips/sector_utils/tc_tracks.py
  geoips/sector_utils/tc_tracks_database.py
  geoips/sector_utils/utils.py
  geoips/sector_utils/yaml_utils.py
  geoips/xarray_utils/data.py
  tests/test_pytest/test_sectors.py
Labels: code checks

#353 352 auto build and deploy sbin and wheels for releases
  .github/workflows/package-and-publish.yaml
  docs/source/releases/v1_11_5a0.rst
Labels: actions
