Repository NRLMMD-GEOIPS/geoips, pull requests merged in 2023-04, with the labels that each got.

#139 117 convert yaml files for boundaries interface
  docs/source/releases/v1_10_0_dev0.rst
  geoips/interface_modules/boundaries/default.yaml
  geoips/interface_modules/boundaries/tc_pmw.yaml
  geoips/interface_modules/boundaries/tc_visir.yaml
  geoips/interface_modules/boundaries/tc_windspeed.yaml
  geoips/schema/plugin_validator.py
Labels: refactor, sprint-april-2023

#140 118 convert yaml files for gridlines interface
  bad_schema/gridlines/bad_tc_windspeed_added_fields.yaml
  bad_schema/gridlines/bad_tc_windspeed_metadata_missing.yaml
  bad_schema/gridlines/bad_tc_windspeed_metadata_types.yaml
  bad_schema/gridlines/bad_tc_windspeed_spec_types.yaml
  bad_schema/gridlines/bad_tc_windspeed_wrong_fields.yaml
  docs/source/releases/v1_10_0_dev0.rst
  geoips/interface_modules/gridlines/default.yaml
  geoips/interface_modules/gridlines/tc_0p25degree.yaml
  geoips/interface_modules/gridlines/tc_pmw.yaml
  geoips/interface_modules/gridlines/tc_visir.yaml
  geoips/interface_modules/gridlines/tc_visir_3200km.yaml
  geoips/interface_modules/gridlines/tc_windspeed.yaml
  geoips/schema/gridlines.yaml
  geoips/schema/plugin_validator.py
Labels: refactor, sprint-april-2023

#154 123 update estimate area extent to output formatted yaml for a sector plugin
  docs/source/releases/v1_10_0_dev0.rst
  geoips/sector_utils/estimate_area_extent.py
Labels: enhancement

#155 Created a base schema that can be referenced by all other interface schemas
  docs/source/releases/v1_10_0_dev0.rst
  geoips/interface_modules/gridlines/tc_pmw.yaml
  geoips/schema/base.yaml
  geoips/schema/boundaries.yaml
  geoips/schema/gridlines.yaml
  geoips/schema/plugin_validator.py
Labels: enhancement, refactor, sprint-april-2023

#145 119 convert yaml files for product intpus interface
  docs/source/releases/v1_10_0_dev0.rst
  geoips/interface_modules/product_inputs/abi.yaml
  geoips/interface_modules/product_inputs/ahi.yaml
  geoips/interface_modules/product_inputs/amsr-e.yaml
  geoips/interface_modules/product_inputs/amsr2.yaml
  geoips/interface_modules/product_inputs/amsu-b.yaml
  geoips/interface_modules/product_inputs/ascat.yaml
  geoips/interface_modules/product_inputs/ascatuhr.yaml
  geoips/interface_modules/product_inputs/atms.yaml
  geoips/interface_modules/product_inputs/gmi.yaml
  geoips/interface_modules/product_inputs/gvar.yaml
  geoips/interface_modules/product_inputs/hscat.yaml
  geoips/interface_modules/product_inputs/imerg.yaml
  geoips/interface_modules/product_inputs/mhs.yaml
  geoips/interface_modules/product_inputs/mimic.yaml
  geoips/interface_modules/product_inputs/modis.yaml
  geoips/interface_modules/product_inputs/oscat.yaml
  geoips/interface_modules/product_inputs/saphir.yaml
  geoips/interface_modules/product_inputs/sar-spd.yaml
  geoips/interface_modules/product_inputs/seviri.yaml
  geoips/interface_modules/product_inputs/smap-spd.yaml
  geoips/interface_modules/product_inputs/smos-spd.yaml
  geoips/interface_modules/product_inputs/ssmi.yaml
  geoips/interface_modules/product_inputs/ssmis.yaml
  geoips/interface_modules/product_inputs/tmi.yaml
  geoips/interface_modules/product_inputs/viirs.yaml
  geoips/interface_modules/product_inputs/windsat.yaml
  geoips/schema/product_inputs.yaml
Labels: enhancement, refactor, sprint-april-2023

#149 created yaml schema for sectors_dynamic interface and converted all associated yaml files to new schema
  docs/source/releases/index.rst
  docs/source/releases/v1_10_0_dev0.rst
  geoips/interface_modules/sectors_dynamic/tc_1024x1024/tc_1km_1024x1024.yaml
  geoips/interface_modules/sectors_dynamic/tc_1024x1024/tc_2km_1024x1024.yaml
  geoips/interface_modules/sectors_dynamic/tc_1400x1400/tc_1km_1400x1400.yaml
  geoips/interface_modules/sectors_dynamic/tc_1400x1400/tc_2km_1400x1400.yaml
  geoips/interface_modules/sectors_dynamic/tc_1600x1600/tc_2km_1600x1600.yaml
  geoips/interface_modules/sectors_dynamic/tc_1600x1600/tc_4km_1600x1600.yaml
  geoips/interface_modules/sectors_dynamic/tc_256x256/tc_4km_256x256.yaml
  geoips/interface_modules/sectors_dynamic/tc_512x512/tc_2km_512x512.yaml
  geoips/interface_modules/sectors_dynamic/tc_512x512/tc_4km_512x512.yaml
  geoips/interface_modules/sectors_dynamic/tc_800x800/tc_2km_800x800.yaml
  geoips/interface_modules/sectors_dynamic/tc_800x800/tc_4km_800x800.yaml
  geoips/interface_modules/sectors_dynamic/tc_huge/tc_0p1km_3200x3200.yaml
  geoips/interface_modules/sectors_dynamic/tc_huge/tc_1km_2500x2500.yaml
  geoips/interface_modules/sectors_dynamic/tc_huge/tc_1km_3200x3200.yaml
  geoips/interface_modules/sectors_dynamic/tc_web_2km_template.yaml
  geoips/interface_modules/sectors_dynamic/tc_web_ascat_high_barbs_template.yaml
  geoips/interface_modules/sectors_dynamic/tc_web_ascatuhr_barbs_template.yaml
  geoips/interface_modules/sectors_dynamic/tc_web_halfkm_template.yaml
  geoips/interface_modules/sectors_dynamic/tc_web_qkm_template.yaml
  geoips/interface_modules/sectors_dynamic/tc_web_template.yaml
  geoips/schema/sectors_dynamic.yaml
  pyproject.toml
Labels: enhancement, refactor, sprint-april-2023

#185 Updating release notes to support 1.10.0a0 release
  docs/source/releases/index.rst
  docs/source/releases/v1_10_0a0.rst
Labels: documentation

#178 v1.10.0a2: 177 update interface name from output format to output formatter throughout code base
  CHANGELOG_mindy.rst
  docs/source/releases/index.rst
  docs/source/releases/v1_10_0a2.rst
  geoips/cli.py
  geoips/commandline/args.py
  geoips/dev/output_config.py
  geoips/dev/product.py
  geoips/interfaces/__init__.py
  geoips/interfaces/output_formatters.py
  geoips/plugins/modules/output_formatters/__init__.py
  geoips/plugins/modules/output_formatters/full_disk_image.py
  geoips/plugins/modules/output_formatters/geotiff_standard.py
  geoips/plugins/modules/output_formatters/imagery_annotated.py
  geoips/plugins/modules/output_formatters/imagery_clean.py
  geoips/plugins/modules/output_formatters/imagery_windbarbs.py
  geoips/plugins/modules/output_formatters/imagery_windbarbs_clean.py
  geoips/plugins/modules/output_formatters/metadata_default.py
  geoips/plugins/modules/output_formatters/metadata_tc.py
  geoips/plugins/modules/output_formatters/netcdf_geoips.py
  geoips/plugins/modules/output_formatters/netcdf_xarray.py
  geoips/plugins/modules/output_formatters/text_winds.py
  geoips/plugins/modules/output_formatters/unprojected_image.py
  geoips/plugins/modules/procflows/config_based.py
  geoips/plugins/modules/procflows/single_source.py
  pyproject.toml
  tests/scripts/abi.static.Infrared.imagery_annotated.sh
  tests/scripts/abi.static.Visible.imagery_annotated.sh
  tests/scripts/ahi.tc.WV.geotiff.sh
  tests/scripts/amsr2.tc.89H-Physical.imagery_annotated.sh
  tests/scripts/amsr2_ocean.tc.windspeed.imagery_clean.sh
  tests/scripts/amsub_mirs.tc.183-3H.imagery_annotated.sh
  tests/scripts/ascat_knmi.tc.windbarbs.imagery_windbarbs_clean.sh
  tests/scripts/ascat_low_knmi.tc.windbarbs.imagery_windbarbs.sh
  tests/scripts/ascat_uhr.tc.wind-ambiguities.imagery_windbarbs.sh
  tests/scripts/atms.tc.165H.netcdf_geoips.sh
  tests/scripts/documentation_imagery.sh
  tests/scripts/ewsg.static.Infrared.imagery_clean.sh
  tests/scripts/gmi.tc.89pct.imagery_clean.sh
  tests/scripts/hy2.tc.windspeed.imagery_annotated.sh
  tests/scripts/imerg.tc.Rain.imagery_clean.sh
  tests/scripts/mimic_coarse.static.TPW-CIMSS.imagery_annotated.sh
  tests/scripts/mimic_fine.tc.TPW-PWAT.imagery_annotated.sh
  tests/scripts/modis.Infrared.unprojected_image.sh
  tests/scripts/oscat_knmi.tc.windbarbs.imagery_windbarbs.sh
  tests/scripts/saphir.tc.183-3HNearest.imagery_annotated.sh
  tests/scripts/sar.tc.nrcs.imagery_annotated.sh
  tests/scripts/seviri.WV-Upper.unprojected_image.sh
  tests/scripts/smap.unsectored.text_winds.sh
  tests/scripts/smos.tc.sectored.text_winds.sh
  tests/scripts/ssmi.tc.37pct.imagery_clean.sh
  tests/scripts/ssmis.color91.unprojected_image.sh
  tests/scripts/viirsclearnight.Night-Vis-IR-GeoIPS1.unprojected_image.sh
  tests/scripts/viirsday.tc.Night-Vis-IR.imagery_annotated.sh
  tests/scripts/viirsmoon.tc.Night-Vis-GeoIPS1.imagery_clean.sh
  tests/yaml_configs/abi_test.yaml
  tests/yaml_configs/abi_test_low_memory.yaml
  tests/yaml_configs/amsr2_test.yaml
  tests/yaml_configs/amsr2_test_low_memory.yaml
Labels: refactor

#180 v1.10.0a3: 179 update interface name from filename format to filename formatter
  docs/source/releases/index.rst
  docs/source/releases/v1_10_0a3.rst
  geoips/cli.py
  geoips/commandline/args.py
  geoips/dev/output_config.py
  geoips/filenames/duplicate_files.py
  geoips/interfaces/__init__.py
  geoips/interfaces/filename_formatters.py
  geoips/plugins/modules/filename_formatters/__init__.py
  geoips/plugins/modules/filename_formatters/basic_fname.py
  geoips/plugins/modules/filename_formatters/geoips_fname.py
  geoips/plugins/modules/filename_formatters/geoips_netcdf_fname.py
  geoips/plugins/modules/filename_formatters/geotiff_fname.py
  geoips/plugins/modules/filename_formatters/metadata_default_fname.py
  geoips/plugins/modules/filename_formatters/tc_clean_fname.py
  geoips/plugins/modules/filename_formatters/tc_fname.py
  geoips/plugins/modules/filename_formatters/text_winds_day_fname.py
  geoips/plugins/modules/filename_formatters/text_winds_full_fname.py
  geoips/plugins/modules/filename_formatters/text_winds_tc_fname.py
  geoips/plugins/modules/filename_formatters/utils/__init__.py
  geoips/plugins/modules/filename_formatters/utils/tc_file_naming.py
  geoips/plugins/modules/procflows/config_based.py
  geoips/plugins/modules/procflows/single_source.py
  pyproject.toml
  tests/scripts/abi.static.Infrared.imagery_annotated.sh
  tests/scripts/abi.static.Visible.imagery_annotated.sh
  tests/scripts/ahi.tc.WV.geotiff.sh
  tests/scripts/amsr2.tc.89H-Physical.imagery_annotated.sh
  tests/scripts/amsr2_ocean.tc.windspeed.imagery_clean.sh
  tests/scripts/amsub_mirs.tc.183-3H.imagery_annotated.sh
  tests/scripts/ascat_knmi.tc.windbarbs.imagery_windbarbs_clean.sh
  tests/scripts/ascat_low_knmi.tc.windbarbs.imagery_windbarbs.sh
  tests/scripts/ascat_uhr.tc.wind-ambiguities.imagery_windbarbs.sh
  tests/scripts/atms.tc.165H.netcdf_geoips.sh
  tests/scripts/documentation_imagery.sh
  tests/scripts/ewsg.static.Infrared.imagery_clean.sh
  tests/scripts/gmi.tc.89pct.imagery_clean.sh
  tests/scripts/hy2.tc.windspeed.imagery_annotated.sh
  tests/scripts/imerg.tc.Rain.imagery_clean.sh
  tests/scripts/mimic_coarse.static.TPW-CIMSS.imagery_annotated.sh
  tests/scripts/mimic_fine.tc.TPW-PWAT.imagery_annotated.sh
  tests/scripts/modis.Infrared.unprojected_image.sh
  tests/scripts/oscat_knmi.tc.windbarbs.imagery_windbarbs.sh
  tests/scripts/saphir.tc.183-3HNearest.imagery_annotated.sh
  tests/scripts/sar.tc.nrcs.imagery_annotated.sh
  tests/scripts/seviri.WV-Upper.unprojected_image.sh
  tests/scripts/smap.unsectored.text_winds.sh
  tests/scripts/smos.tc.sectored.text_winds.sh
  tests/scripts/ssmi.tc.37pct.imagery_clean.sh
  tests/scripts/ssmis.color91.unprojected_image.sh
  tests/scripts/viirsclearnight.Night-Vis-IR-GeoIPS1.unprojected_image.sh
  tests/scripts/viirsday.tc.Night-Vis-IR.imagery_annotated.sh
  tests/scripts/viirsmoon.tc.Night-Vis-GeoIPS1.imagery_clean.sh
  tests/yaml_configs/abi_test.yaml
  tests/yaml_configs/abi_test_low_memory.yaml
  tests/yaml_configs/amsr2_test.yaml
  tests/yaml_configs/amsr2_test_low_memory.yaml
Labels: refactor

#184 v1_10_0a5: 183 finalize interface names for sector loaders and sector adjusters
  docs/source/releases/index.rst
  docs/source/releases/v1_10_0a5.rst
  geoips/commandline/args.py
  geoips/plugins/modules/procflows/single_source.py
  geoips/plugins/modules/sector_loaders/dynamic/__init__.py
  geoips/plugins/modules/sector_loaders/dynamic/clat_clon_resolution_shape.py
  geoips/plugins/modules/sector_loaders/trackfiles/__init__.py
  geoips/plugins/modules/sector_loaders/trackfiles/bdeck_parser.py
  geoips/plugins/modules/sector_loaders/trackfiles/flat_sectorfile_parser.py
  geoips/plugins/yaml/sectors/dynamic/tc_1024x1024/tc_1km_1024x1024.yaml
  geoips/plugins/yaml/sectors/dynamic/tc_1024x1024/tc_2km_1024x1024.yaml
  geoips/plugins/yaml/sectors/dynamic/tc_1400x1400/tc_1km_1400x1400.yaml
  geoips/plugins/yaml/sectors/dynamic/tc_1400x1400/tc_2km_1400x1400.yaml
  geoips/plugins/yaml/sectors/dynamic/tc_1600x1600/tc_2km_1600x1600.yaml
  geoips/plugins/yaml/sectors/dynamic/tc_1600x1600/tc_4km_1600x1600.yaml
  geoips/plugins/yaml/sectors/dynamic/tc_256x256/tc_4km_256x256.yaml
  geoips/plugins/yaml/sectors/dynamic/tc_512x512/tc_2km_512x512.yaml
  geoips/plugins/yaml/sectors/dynamic/tc_512x512/tc_4km_512x512.yaml
  geoips/plugins/yaml/sectors/dynamic/tc_800x800/tc_2km_800x800.yaml
  geoips/plugins/yaml/sectors/dynamic/tc_800x800/tc_4km_800x800.yaml
  geoips/plugins/yaml/sectors/dynamic/tc_huge/tc_0p1km_3200x3200.yaml
  geoips/plugins/yaml/sectors/dynamic/tc_huge/tc_1km_2500x2500.yaml
  geoips/plugins/yaml/sectors/dynamic/tc_huge/tc_1km_3200x3200.yaml
  geoips/plugins/yaml/sectors/dynamic/tc_web_2km_template.yaml
  geoips/plugins/yaml/sectors/dynamic/tc_web_ascat_high_barbs_template.yaml
  geoips/plugins/yaml/sectors/dynamic/tc_web_ascatuhr_barbs_template.yaml
  geoips/plugins/yaml/sectors/dynamic/tc_web_halfkm_template.yaml
  geoips/plugins/yaml/sectors/dynamic/tc_web_qkm_template.yaml
  geoips/plugins/yaml/sectors/dynamic/tc_web_template.yaml
  geoips/plugins/yaml/sectors/static/ewsg.yaml
  geoips/plugins/yaml/sectors/static/global.yaml
  geoips/plugins/yaml/sectors/static/goes16.yaml
  geoips/plugins/yaml/sectors/static/goes17.yaml
  geoips/plugins/yaml/sectors/static/himawari8.yaml
  geoips/sector_utils/tc_tracks.py
  geoips/sector_utils/utils.py
  pyproject.toml
  tests/scripts/abi.static.Infrared.imagery_annotated.sh
  tests/scripts/abi.static.Visible.imagery_annotated.sh
  tests/scripts/documentation_imagery.sh
  tests/scripts/ewsg.static.Infrared.imagery_clean.sh
  tests/scripts/mimic_coarse.static.TPW-CIMSS.imagery_annotated.sh
  tests/yaml_configs/abi_test.yaml
  tests/yaml_configs/abi_test_low_memory.yaml
  tests/yaml_configs/amsr2_test.yaml
  tests/yaml_configs/amsr2_test_low_memory.yaml
Labels: refactor

#187 v1.10.0a6: 186 finalize naming for feature annotators and gridline annotators
  docs/source/releases/v1_10_0a6.rst
  geoips/plugins/yaml/feature_annotators/default.yaml
  geoips/plugins/yaml/feature_annotators/tc_pmw.yaml
  geoips/plugins/yaml/feature_annotators/tc_visir.yaml
  geoips/plugins/yaml/feature_annotators/tc_windspeed.yaml
  geoips/plugins/yaml/gridline_annotators/default.yaml
  geoips/plugins/yaml/gridline_annotators/tc_0p25degree.yaml
  geoips/plugins/yaml/gridline_annotators/tc_pmw.yaml
  geoips/plugins/yaml/gridline_annotators/tc_visir.yaml
  geoips/plugins/yaml/gridline_annotators/tc_visir_3200km.yaml
  geoips/plugins/yaml/gridline_annotators/tc_windspeed.yaml
Labels: refactor

#196 v1.10.0a9: 195 move sector loadersdynamic back to sector generators
  docs/source/releases/index.rst
  docs/source/releases/v1_10_0a9.rst
  geoips/commandline/args.py
  geoips/plugins/modules/procflows/single_source.py
  geoips/plugins/modules/sector_metadata_generators/__init__.py
  geoips/plugins/modules/sector_metadata_generators/bdeck_parser.py
  geoips/plugins/modules/sector_metadata_generators/tc_sector_file_parser.py
  geoips/plugins/modules/sector_spec_generators/__init__.py
  geoips/plugins/modules/sector_spec_generators/center_coordinates.py
  geoips/plugins/yaml/sectors/dynamic/tc_1024x1024/tc_1km_1024x1024.yaml
  geoips/plugins/yaml/sectors/dynamic/tc_1024x1024/tc_2km_1024x1024.yaml
  geoips/plugins/yaml/sectors/dynamic/tc_1400x1400/tc_1km_1400x1400.yaml
  geoips/plugins/yaml/sectors/dynamic/tc_1400x1400/tc_2km_1400x1400.yaml
  geoips/plugins/yaml/sectors/dynamic/tc_1600x1600/tc_2km_1600x1600.yaml
  geoips/plugins/yaml/sectors/dynamic/tc_1600x1600/tc_4km_1600x1600.yaml
  geoips/plugins/yaml/sectors/dynamic/tc_256x256/tc_4km_256x256.yaml
  geoips/plugins/yaml/sectors/dynamic/tc_512x512/tc_2km_512x512.yaml
  geoips/plugins/yaml/sectors/dynamic/tc_512x512/tc_4km_512x512.yaml
  geoips/plugins/yaml/sectors/dynamic/tc_800x800/tc_2km_800x800.yaml
  geoips/plugins/yaml/sectors/dynamic/tc_800x800/tc_4km_800x800.yaml
  geoips/plugins/yaml/sectors/dynamic/tc_huge/tc_0p1km_3200x3200.yaml
  geoips/plugins/yaml/sectors/dynamic/tc_huge/tc_1km_2500x2500.yaml
  geoips/plugins/yaml/sectors/dynamic/tc_huge/tc_1km_3200x3200.yaml
  geoips/plugins/yaml/sectors/dynamic/tc_web_2km_template.yaml
  geoips/plugins/yaml/sectors/dynamic/tc_web_ascat_high_barbs_template.yaml
  geoips/plugins/yaml/sectors/dynamic/tc_web_ascatuhr_barbs_template.yaml
  geoips/plugins/yaml/sectors/dynamic/tc_web_halfkm_template.yaml
  geoips/plugins/yaml/sectors/dynamic/tc_web_qkm_template.yaml
  geoips/plugins/yaml/sectors/dynamic/tc_web_template.yaml
  geoips/sector_utils/tc_tracks.py
  geoips/sector_utils/utils.py
  geoips/yaml_configs/sectors_dynamic/tc_1024x1024/tc_1km_1024x1024.yaml
  geoips/yaml_configs/sectors_dynamic/tc_1024x1024/tc_2km_1024x1024.yaml
  geoips/yaml_configs/sectors_dynamic/tc_1400x1400/tc_1km_1400x1400.yaml
  geoips/yaml_configs/sectors_dynamic/tc_1400x1400/tc_2km_1400x1400.yaml
  geoips/yaml_configs/sectors_dynamic/tc_1600x1600/tc_2km_1600x1600.yaml
  geoips/yaml_configs/sectors_dynamic/tc_1600x1600/tc_4km_1600x1600.yaml
  geoips/yaml_configs/sectors_dynamic/tc_256x256/tc_4km_256x256.yaml
  geoips/yaml_configs/sectors_dynamic/tc_512x512/tc_2km_512x512.yaml
  geoips/yaml_configs/sectors_dynamic/tc_512x512/tc_4km_512x512.yaml
  geoips/yaml_configs/sectors_dynamic/tc_800x800/tc_2km_800x800.yaml
  geoips/yaml_configs/sectors_dynamic/tc_800x800/tc_4km_800x800.yaml
  geoips/yaml_configs/sectors_dynamic/tc_huge/tc_0p1km_3200x3200.yaml
  geoips/yaml_configs/sectors_dynamic/tc_huge/tc_1km_2500x2500.yaml
  geoips/yaml_configs/sectors_dynamic/tc_huge/tc_1km_3200x3200.yaml
  geoips/yaml_configs/sectors_dynamic/tc_web_2km_template.yaml
  geoips/yaml_configs/sectors_dynamic/tc_web_ascat_high_barbs_template.yaml
  geoips/yaml_configs/sectors_dynamic/tc_web_ascatuhr_barbs_template.yaml
  geoips/yaml_configs/sectors_dynamic/tc_web_halfkm_template.yaml
  geoips/yaml_configs/sectors_dynamic/tc_web_qkm_template.yaml
  geoips/yaml_configs/sectors_dynamic/tc_web_template.yaml
  pyproject.toml
Labels: refactor, breaking change
