Repository NRLMMD-GEOIPS/geoips, pull requests merged in 2023-08, with the labels that each got.

#244 added slack channel to geoips/README.md per a feature request
  README.md
Labels: enhancement

#243 Update Coverage Checkers to use either varname or product name
  geoips/interfaces/module_based/coverage_checkers.py
  geoips/plugins/modules/coverage_checkers/center_radius.py
  geoips/plugins/modules/coverage_checkers/center_radius_rgba.py
  geoips/plugins/modules/coverage_checkers/masked_arrays.py
  geoips/plugins/modules/coverage_checkers/numpy_arrays_nan.py
  geoips/plugins/modules/coverage_checkers/rgba.py
  geoips/plugins/modules/coverage_checkers/windbarbs.py
Labels: refactor

#242 Implement find_ascii_palette for TPW colormaps
  geoips/plugins/modules/colormappers/tpw/tpw_cimss.py
  geoips/plugins/modules/colormappers/tpw/tpw_purple.py
  geoips/plugins/modules/colormappers/tpw/tpw_pwat.py
Labels: refactor

#252 Create v1_11_1a0.rst release notes
  docs/source/releases/v1_11_1a0.rst
Labels: documentation

#269 Require sphinx<7.2
  docs/source/releases/v1_11_3a0.rst
  pyproject.toml
Labels: bug

#270 Resolve typos in installation instructions
  docs/source/starter/installation.rst
Labels: bug

#271 Add 1.11.3a0 to release note index
  docs/source/releases/index.rst
  docs/source/releases/v1_11_3a0.rst
Labels: bug

#272 Add .vscode repository to full_install.sh
  docs/source/releases/v1_11_3a0.rst
  setup/check_system_requirements.sh
  tests/integration_tests/full_install.sh
Labels: installation

#273 Add setup script with explicit paths to installation locations
  docs/source/releases/v1_11_3a0.rst
  setup/USER_MODIFY_config
Labels: installation

#278 Remove vim8 steps, clarify documentation and style descriptions
  docs/source/devguide/documentation_strategy.rst
Labels: documentation

#283 282 update tpw colormaps to use mpl norm
  docs/source/releases/v1_11_3a0.rst
  docs/source/starter/index.rst
  geoips/plugins/modules/colormappers/matplotlib_linear_norm.py
  geoips/plugins/modules/colormappers/tpw/tpw_cimss.py
  geoips/plugins/modules/colormappers/tpw/tpw_purple.py
  geoips/plugins/yaml/product_defaults/tpw/TPW-CIMSS.yaml
  geoips/plugins/yaml/product_defaults/tpw/TPW-PURPLE.yaml
  pyproject.toml
Labels: refactor

#292 285 Create Interactive Log Level and update procflows to include useful interactive log outputs
  docs/source/releases/v1_11_3a0.rst
  geoips/commandline/args.py
  geoips/commandline/log_setup.py
  geoips/commandline/run_procflow.py
  geoips/compare_outputs.py
  geoips/geoips_utils.py
  geoips/image_utils/mpl_utils.py
  geoips/plugins/modules/procflows/config_based.py
  geoips/plugins/modules/procflows/single_source.py
  geoips/plugins/modules/readers/abi_netcdf.py
  geoips/plugins/modules/readers/ahi_hsd.py
  geoips/plugins/modules/readers/utils/geostationary_geolocation.py
Labels: refactor

#306 Pass variables and product_name to xarray_to_xarray algs
  docs/source/releases/v1_11_3a0.rst
  geoips/interfaces/module_based/algorithms.py
  geoips/plugins/modules/procflows/single_source.py
Labels: bug

#307 Handle xarray in apply_data_range
  docs/source/releases/v1_11_3a0.rst
  geoips/data_manipulations/corrections.py
Labels: bug
