Repository NRLMMD-GEOIPS/geoips, pull requests merged in 2023-10, with the labels that each got.

#360 v1.11.5 geoips - VERSION RELEASE - short summary
  .github/workflows/check-code.yaml
  .github/workflows/package-and-publish.yaml
  .github/workflows/release-note-update.yaml
  docs/source/releases/index.rst
  docs/source/releases/v1_11_3.rst
  docs/source/releases/v1_11_5.rst
  geoips/plugins/modules/readers/ssmis_binary.py
  tests/integration_tests/full_test.sh
  tests/test_all.sh
  tests/utils/check_code.sh
  update_this_release_note
Labels: Version Release

#356 356 add windows & pip install instructions
  README.md
  docs/source/releases/v1_11_5a0.rst
  docs/source/releases/v1_11_7a0.rst
  docs/source/starter/installation.rst
  docs/source/starter/mac_installation.rst
  docs/source/starter/windows_installation.rst
Labels: documentation

#343 322 Replace local path links within documentation with sphinx 'ref' links
  docs/source/releases/index.rst
  docs/source/releases/v1_11_5a0.rst
  docs/source/releases/v1_11_7a0.rst
  docs/source/starter/expert_installation.rst
  docs/source/starter/extending.rst
  docs/source/starter/index.rst
  docs/source/starter/installation.rst
  docs/source/starter/windows_installation.rst
  docs/source/userguide/plugin_extend.rst
Labels: documentation

#345 337 Fixed Scipy import deprecation warning
  docs/source/releases/v1_11_7a0.rst
  geoips/plugins/modules/readers/abi_netcdf.py
  geoips/plugins/modules/readers/ahi_hsd.py
  pyproject.toml
Labels: deprecation

#361 30 Make geotiffs right side up
  docs/source/releases/v1_11_5a0.rst
  docs/source/releases/v1_11_7a0.rst
  geoips/plugins/modules/output_formatters/geotiff_standard.py
  tests/outputs/ahi.tc.WV.geotiff/20200405_000000_SH252020_ahi_himawari-8_WV_100kts_100p00_1p0.tif
Labels: bug

#351 293 Convert compare_outputs.py into an 'output_checkers' interface
  docs/source/releases/v1_11_7a0.rst
  geoips/compare_outputs.py
  geoips/interfaces/__init__.py
  geoips/interfaces/base.py
  geoips/interfaces/module_based/output_checkers.py
  geoips/plugins/modules/output_checkers/geotiff.py
  geoips/plugins/modules/output_checkers/image.py
  geoips/plugins/modules/output_checkers/netcdf.py
  geoips/plugins/modules/output_checkers/text.py
  geoips/plugins/modules/procflows/config_based.py
  geoips/plugins/modules/procflows/single_source.py
  pyproject.toml
Labels: enhancement, refactor

#359 358 datatree and pytest
  docs/source/releases/v1_11_7a0.rst
  geoips/xarray_utils/xr_to_dtree.py
  tests/test_pytest/test_dtree.py
Labels: enhancement, good first issue, actions

#369 368 convert plugin module to obj to class method
  docs/source/releases/v1_11_7a0.rst
  geoips/interfaces/base.py
Labels: refactor

#367 Create "output_checker_kwargs" Argument
  docs/source/releases/v1_11_7a0.rst
  geoips/commandline/args.py
  geoips/interfaces/module_based/output_checkers.py
  geoips/plugins/modules/output_checkers/geotiff.py
  geoips/plugins/modules/output_checkers/image.py
  geoips/plugins/modules/output_checkers/netcdf.py
  geoips/plugins/modules/output_checkers/text.py
  geoips/plugins/modules/procflows/config_based.py
  geoips/plugins/modules/procflows/single_source.py
Labels: enhancement, refactor

#240 238 added create_plugin_registries.py to run during installation
  docs/source/releases/v1_11_7a0.rst
  geoips/create_plugin_registries.py
  geoips/errors.py
  geoips/geoips_utils.py
  geoips/interfaces/base.py
  geoips/interfaces/yaml_based/products.py
  geoips/interfaces/yaml_based/sectors.py
  geoips/sector_utils/utils.py
  pyproject.toml
Labels: enhancement, Dev Update, installation

#391 387 add text plugins to registries
  docs/source/releases/v1_11_7a0.rst
  geoips/create_plugin_registries.py
Labels: refactor

#379 378 attach unit test functionality to output checker plugins
  docs/source/releases/v1_11_7a0.rst
  geoips/commandline/log_setup.py
  geoips/plugins/modules/output_checkers/geotiff.py
  geoips/plugins/modules/output_checkers/image.py
  geoips/plugins/modules/output_checkers/netcdf.py
  geoips/plugins/modules/output_checkers/text.py
  tests/unit_tests/plugins/modules/output_checkers/test_output_checkers.py
  tests/unit_tests/plugins/yaml/sectors/test_sectors.py
  tests/unit_tests/plugins/yaml/test_all_yaml_plugins.py
  tests/unit_tests/schema/bad/bases/docstring.yaml
  tests/unit_tests/schema/bad/bases/valid_identifier.yaml
  tests/unit_tests/schema/bad/feature_annotators/cartopy.yaml
  tests/unit_tests/schema/bad/gridline_annotators/cartopy.yaml
  tests/unit_tests/schema/bad/product_defaults/algorithm_colormapper.yaml
  tests/unit_tests/schema/bad/product_defaults/algorithm_interpolator_colormapper.yaml
  tests/unit_tests/schema/bad/product_defaults/bases/algorithm.yaml
  tests/unit_tests/schema/bad/product_defaults/bases/colormapper.yaml
  tests/unit_tests/schema/bad/product_defaults/bases/coverage_checker.yaml
  tests/unit_tests/schema/bad/product_defaults/bases/interpolator.yaml
  tests/unit_tests/schema/bad/product_defaults/interpolator_algorithm.yaml
  tests/unit_tests/schema/bad/product_defaults/interpolator_algorithm_colormapper.yaml
  tests/unit_tests/schema/bad/products/bases/product.yaml
  tests/unit_tests/schema/bad/products/single.yaml
  tests/unit_tests/schema/good/bases/valid_identifier.yaml
  tests/unit_tests/schema/good/feature_annotators/cartopy.yaml
  tests/unit_tests/schema/good/gridline_annotators/cartopy.yaml
  tests/unit_tests/schema/good/product_defaults/algorithm_colormapper.yaml
  tests/unit_tests/schema/good/product_defaults/algorithm_interpolator_colormapper.yaml
  tests/unit_tests/schema/good/product_defaults/bases/algorithm.yaml
  tests/unit_tests/schema/good/product_defaults/bases/colormapper.yaml
  tests/unit_tests/schema/good/product_defaults/bases/coverage_checker.yaml
  tests/unit_tests/schema/good/product_defaults/bases/interpolator.yaml
  tests/unit_tests/schema/good/product_defaults/interpolator_algorithm.yaml
  tests/unit_tests/schema/good/product_defaults/interpolator_algorithm_colormapper.yaml
  tests/unit_tests/schema/good/products/bases/product.yaml
  tests/unit_tests/schema/good/products/single.yaml
  tests/unit_tests/schema/good/sectors/static.yaml
  tests/unit_tests/schema/test_yaml_schema.py
  tests/unit_tests/test_dtree.py
Labels: testing, refactor

#384 382 raise error for duplicate plugins
  docs/source/releases/v1_11_7a0.rst
  geoips/create_plugin_registries.py
  geoips/geoips_utils.py
  tests/unit_tests/test_dtree.py
Labels: bug, testing
