Repository NRLMMD-GEOIPS/geoips, pull requests merged in 2024-10, with the labels that each got.

#505 Add numpy standards 502
  docs/source/new-docs/contribute/coding_standards.rst
  docs/source/releases/latest/numpy-standards.yaml
Labels: documentation

#793 Fix failing base tests - path replacement bug
  docs/source/releases/latest/fix-env-var-sub.yaml
  geoips/geoips_utils.py
Labels: bug

#796 AMI and EWSG Refactor: Multi-scan time functionality
  docs/source/releases/latest/ami-ewsg-multi-scan-time.yaml
  geoips/interfaces/module_based/readers.py
  geoips/plugins/modules/readers/abi_netcdf.py
  geoips/plugins/modules/readers/ahi_hsd.py
  geoips/plugins/modules/readers/ami_netcdf.py
  geoips/plugins/modules/readers/ewsg_netcdf.py
  geoips/plugins/modules/readers/seviri_hrit.py
  geoips/plugins/yaml/sectors/static/korea.yaml
Labels: enhancement, refactor

#739 New ``geoips list source-names`` CLI command
  docs/source/releases/latest/CLI-geoips-list-source-names.yaml
  docs/source/userguide/command_line.rst
  geoips/commandline/ancillary_info/alias_mapping.yaml
  geoips/commandline/ancillary_info/cmd_instructions.yaml
  geoips/commandline/geoips_list.py
  geoips/commandline/log_setup.py
  geoips/create_plugin_registries.py
  geoips/plugins/modules/readers/abi_l2_netcdf.py
  geoips/plugins/modules/readers/abi_netcdf.py
  geoips/plugins/modules/readers/ahi_hsd.py
  geoips/plugins/modules/readers/ami_netcdf.py
  geoips/plugins/modules/readers/amsr2_netcdf.py
  geoips/plugins/modules/readers/amsr2_remss_winds_netcdf.py
  geoips/plugins/modules/readers/amsub_hdf.py
  geoips/plugins/modules/readers/amsub_mirs.py
  geoips/plugins/modules/readers/ascat_uhr_netcdf.py
  geoips/plugins/modules/readers/atms_hdf5.py
  geoips/plugins/modules/readers/ewsg_netcdf.py
  geoips/plugins/modules/readers/geoips_netcdf.py
  geoips/plugins/modules/readers/gmi_hdf5.py
  geoips/plugins/modules/readers/imerg_hdf5.py
  geoips/plugins/modules/readers/mimic_netcdf.py
  geoips/plugins/modules/readers/modis_hdf4.py
  geoips/plugins/modules/readers/saphir_hdf5.py
  geoips/plugins/modules/readers/sar_winds_netcdf.py
  geoips/plugins/modules/readers/scat_knmi_winds_netcdf.py
  geoips/plugins/modules/readers/scat_noaa_winds_netcdf.py
  geoips/plugins/modules/readers/seviri_hrit.py
  geoips/plugins/modules/readers/sfc_winds_text.py
  geoips/plugins/modules/readers/smap_remss_winds_netcdf.py
  geoips/plugins/modules/readers/smos_winds_netcdf.py
  geoips/plugins/modules/readers/ssmi_binary.py
  geoips/plugins/modules/readers/ssmis_binary.py
  geoips/plugins/modules/readers/viirs_netcdf.py
  geoips/plugins/modules/readers/viirs_sdr_hdf5.py
  geoips/plugins/modules/readers/wfabba_ascii.py
  geoips/plugins/modules/readers/windsat_idr37_binary.py
  geoips/plugins/modules/readers/windsat_remss_winds_netcdf.py
  tests/unit_tests/commandline/test_geoips_list_source_names.py
Labels: enhancement, cli, 2024-workshop
