Repository NRLMMD-GEOIPS/geoips, pull requests merged in 2024-04, with the labels that each got.

#401 377 add log with emphasis function
  .gitignore
  docs/source/releases/v1_12_2a0.rst
  geoips/commandline/log_setup.py
  geoips/interfaces/module_based/output_checkers.py
  geoips/plugins/modules/output_checkers/geotiff.py
  geoips/plugins/modules/output_checkers/image.py
  geoips/plugins/modules/output_checkers/netcdf.py
  geoips/plugins/modules/output_checkers/text.py
  geoips/plugins/modules/procflows/single_source.py
  tests/unit_tests/commandline/log_setup.py
  tests/unit_tests/commandline/test_log_setup.py
Labels: enhancement, refactor

#452 Rewrite Dockerfile so build completes
  Dockerfile
  docs/source/releases/v1_12_2a0.rst
Labels: bug, installation

#467 Documentation additions: Summary and Structure
  docs/dev/coding_standards.rst
  docs/source/releases/v1_12_2a0.rst
Labels: documentation

#434 Polar Imagery Bug with Pyresample
  docs/source/releases/v1_12_2a0.rst
  geoips/plugins/modules/procflows/single_source.py
  geoips/plugins/yaml/gridline_annotators/north_pole.yaml
  geoips/plugins/yaml/sectors/static/abu_dhabi.yaml
  geoips/plugins/yaml/sectors/static/north_pole.yaml
  geoips/plugins/yaml/sectors/static/south_pole.yaml
  geoips/xarray_utils/data.py
  tests/scripts/viirsclearnight.Night-Vis-IR-GeoIPS1.imagery_annotated.sh
  tests/test_all.sh
  tests/unit_tests/xarray_utils/data.py
Labels: bug

#489 Implementing Standards for Placing Imports
  docs/dev/coding_standards.rst
  docs/source/releases/v1_12_2a0.rst
Labels: documentation, discussion required

#438 Clean up optional dependencies throughout GeoIPS Code
  docs/source/releases/v1_12_2a0.rst
  geoips/plugins/modules/procflows/config_based.py
  geoips/plugins/modules/readers/abi_netcdf.py
  geoips/plugins/modules/readers/ahi_hsd.py
  geoips/plugins/modules/readers/ewsg_netcdf.py
  geoips/plugins/modules/readers/modis_hdf4.py
  geoips/plugins/modules/readers/seviri_hrit.py
  geoips/plugins/modules/readers/utils/geostationary_geolocation.py
  geoips/plugins/modules/readers/viirs_netcdf.py
  geoips/utils/context_managers.py
  geoips/utils/memusg.py
  tests/unit_tests/utils/context_managers.py
Labels: refactor

#442 Move PyTest functionality from PluginRegistry Class to Unit Tests
  docs/source/releases/index.rst
  docs/source/releases/v1_12_2a0.rst
  geoips/plugin_registry.py
  tests/unit_tests/plugin_registries/test_plugin_registries.py
Labels: testing, refactor, regression

#503 Add PEP8 to Standards Doc
  docs/dev/coding_standards.rst
  docs/source/releases/v1_12_2a0.rst
Labels: documentation

#400 Create Documentation For PluginRegistry
  docs/source/_templates/conf_PKG.py
  docs/source/releases/v1_12_2a0.rst
  docs/source/userguide/index.rst
  docs/source/userguide/plugin_registries.rst
  geoips/create_plugin_registries.py
  pyproject.toml
Labels: documentation

#500 Update Coding Standards Documentation for Code Standardization Process
  docs/dev/coding_standards.rst
  docs/source/releases/v1_12_2a0.rst
Labels: documentation

#497 fixed bugs introduced by finish log with emphasis pr
  docs/source/releases/v1_12_2a0.rst
  geoips/commandline/log_setup.py
  tests/unit_tests/commandline/test_log_setup.py
Labels: bug

#508 v1.13.0a0 geoips - UPDATE THIS RELEASE_NOTE - Update update_this_release_note to v1_13_0a0.rst
  docs/source/releases/index.rst
  docs/source/releases/v1_13_0a0.rst
  update_this_release_note
Labels: Dev Update
