Repository NRLMMD-GEOIPS/geoips, pull requests merged in 2024-07, with the labels that each got.

#670 WORKSHOP Fix failing CLI test data unit tests to ensure CI passes
  DISTRIBUTION
  LICENSE
  docs/source/releases/index.rst
  docs/source/releases/v1_14_0a0.rst
  geoips/plugins/modules/procflows/single_source.py
  tests/unit_tests/commandline/cli_top_level_tester.py
  tests/unit_tests/commandline/test_geoips_config_install.py
  tests/unit_tests/commandline/test_log_setup.py
Labels: bug, 2024-workshop

#671 WORKSHOP Resolve xrdict_area_product_to_outlist family output formatter error
  docs/source/releases/v1_14_0a0.rst
  geoips/plugins/modules/procflows/single_source.py
Labels: bug, 2024-workshop

#528 274 Expose All GeoIPS Commands
  docs/source/releases/v1_13_0a0.rst
  docs/source/releases/v1_14_0a0.rst
  geoips/errors.py
  geoips/geoips_utils.py
  geoips/plugins/modules/readers/seviri_hrit.py
  geoips/plugins/modules/readers/windsat_remss_winds_netcdf.py
  pyproject.toml
  tests/unit_tests/commandline/test_expose.py
  tests/unit_tests/commandline/test_geoips_validate.py
Labels: enhancement, cli, Brassy

#669 Documentation better release notes
  docs/source/releases/index.rst
  docs/source/releases/v1_14_0a0/documentation-better-release-notes.yaml
Labels: documentation

#686 WORKSHOP BUG FIXES cartopy test output version, remove failing cmd_instructions unit test, do not hard code repos with console scripts in expose unit test, remove duplicate log statements, remove template_fusion_plugin tests
  docs/source/releases/latest/0-pre-existing-conditions.yaml
  docs/source/releases/latest/666-final-bug-fixes-prior-to-workshop-2.yaml
  docs/source/releases/latest/679-add-brassy-to-ci.yaml
  docs/source/releases/latest/documentation-better-release-notes.yaml
  docs/source/releases/v1_14_0a0/0-pre-existing-conditions.yaml
  docs/source/releases/v1_14_0a0/documentation-better-release-notes.yaml
  environments/mamba_base_package_list_1.13.0_20240713.yml
  environments/mamba_full_package_list_1.13.0_20240717.yml
  environments/pip_base_requirements_1.13.0_20240713.txt
  environments/pip_full_requirements_1.13.0_20240717.txt
  geoips/commandline/commandline_interface.py
  geoips/commandline/log_setup.py
  pyproject.toml
  tests/integration_tests/full_install.sh
  tests/integration_tests/full_test.sh
  tests/unit_tests/commandline/cmd_instructions/json_newer/cmd_instructions.json
  tests/unit_tests/commandline/cmd_instructions/json_newer/cmd_instructions.yaml
  tests/unit_tests/commandline/cmd_instructions/yaml_newer/cmd_instructions.json
  tests/unit_tests/commandline/cmd_instructions/yaml_newer/cmd_instructions.yaml
  tests/unit_tests/commandline/test_expose.py
  tests/unit_tests/commandline/test_get_commandline_instructions.py
Labels: bug, 2024-workshop

#691 WORKSHOP BUG FIX Updating pytest_long to be called via all_test_data
  docs/source/releases/latest/666-final-bug-fixes-prior-to-workshop-3.yaml
  tests/utils/check_code.sh
Labels: bug

#692 WORKSHOP BUG FIX update build_docs.sh to auto-generate release notes with brassy
  .gitignore
  docs/build_docs.sh
  docs/source/releases/index.rst
  docs/source/releases/latest.rst
  docs/source/releases/latest/666-final-bug-fixes-prior-to-workshop-4.yaml
  docs/update_release_note_index.py
Labels: bug, documentation

#697 WORKSHOP BUG FIX: Ensure return value correctly captured from import package within build_docs.sh
  docs/build_docs.sh
  docs/source/releases/latest/666-final-bug-fixes-prior-to-workshop-6.yaml
Labels: bug

#699 WORKSHOP BUG FIX: Revert docs/source/releases/index.rst after build_docs.sh
  docs/build_docs.sh
  docs/source/releases/latest/666-final-bug-fixes-prior-to-workshop-7.yaml
Labels: bug

#668 Memusg bug with MacOS
  docs/source/releases/latest/memusg-bug-with-mac.yaml
  geoips/utils/memusg.py
Labels: bug, 2024-workshop

#703 Improve error message for bad python version check_system_requirement…
  docs/source/releases/latest/665-issue-with-install-on-debian.yaml
  setup/check_system_requirements.sh
Labels: bug, installation, 2024-workshop

#705 Mac image match bug
  docs/source/releases/latest/mac-image-match-bug.yaml
  environments/mamba_full_package_list_1.13.0_20240724.yml
  environments/pip_full_requirements_1.13.0_20240724.txt
  geoips/plugins/modules/output_checkers/image.py
Labels: bug, 2024-workshop

#642 CLI class factory
  docs/source/releases/latest/575-cli-class-factory.yaml
  docs/source/userguide/command_line.rst
  geoips/commandline/ancillary_info/cmd_instructions.yaml
  geoips/commandline/geoips_command.py
  geoips/commandline/geoips_list.py
  tests/unit_tests/commandline/cli_top_level_tester.py
  tests/unit_tests/commandline/test_geoips_list_interface.py
Labels: refactor, cli, 2024-workshop

#641 627 New 'geoips tree' command
  docs/source/releases/latest/627-CLI-tree.yaml
  docs/source/userguide/command_line.rst
  geoips/commandline/ancillary_info/cmd_instructions.yaml
  geoips/commandline/commandline_interface.py
  geoips/commandline/geoips_tree.py
  geoips/filenames/base_paths.py
  tests/unit_tests/commandline/cli_top_level_tester.py
  tests/unit_tests/commandline/test_geoips_tree.py
Labels: enhancement, cli, 2024-workshop

#644 576 get cmd class factories
  .github/workflows_archived/check-old-docs-frozen.yaml
  .gitignore
  docs/source/_templates/conf_PKG.py
  docs/source/releases/latest/576-get-cmd-class-factories.yaml
  docs/source/userguide/command_line.rst
  geoips/commandline/ancillary_info/alias_mapping.yaml
  geoips/commandline/ancillary_info/cmd_instructions.yaml
  geoips/commandline/cmd_instructions.py
  geoips/commandline/commandline_interface.py
  geoips/commandline/geoips_command.py
  geoips/commandline/geoips_get.py
  geoips/commandline/geoips_list.py
  pyproject.toml
  tests/unit_tests/commandline/cli_top_level_tester.py
  tests/unit_tests/commandline/test_geoips_get_family.py
  tests/unit_tests/commandline/test_geoips_get_interface.py
  tests/unit_tests/commandline/test_geoips_get_package.py
  tests/unit_tests/commandline/test_geoips_get_plugin.py
  tests/unit_tests/commandline/test_geoips_list_interface.py
  tests/unit_tests/commandline/test_geoips_list_interfaces.py
  tests/unit_tests/commandline/test_geoips_list_packages.py
  tests/unit_tests/commandline/test_geoips_list_plugins.py
  tests/unit_tests/commandline/test_geoips_list_scripts.py
  tests/unit_tests/commandline/test_geoips_list_test_datasets.py
  tests/unit_tests/commandline/test_geoips_list_unit_tests.py
  tests/unit_tests/commandline/test_geoips_run.py
  tests/unit_tests/commandline/test_geoips_test_linting.py
  tests/unit_tests/commandline/test_geoips_test_script.py
  tests/unit_tests/commandline/test_geoips_test_unit_test.py
  tests/unit_tests/commandline/test_geoips_tree.py
  tests/unit_tests/commandline/test_geoips_validate.py
  tests/unit_tests/commandline/test_get_commandline_instructions.py
Labels: refactor, cli, 2024-workshop

#659 Apply Scope to CLI Arguments
  docs/source/releases/latest/637-use-parse-known-args-to-apply-scope-to-CLI-arguments.yaml
  geoips/commandline/commandline_interface.py
  geoips/commandline/geoips_command.py
  tests/unit_tests/commandline/cli_top_level_tester.py
Labels: refactor, cli, 2024-workshop

#663 Merge ``create_sector_image`` functionality into the CLI
  docs/source/images/command_line_examples/canada.png
  docs/source/releases/latest/636-merge-create_sector_image-functionality-into-CLI.yaml
  docs/source/userguide/command_line.rst
  docs/source/userguide/plugin_development/static_sector.rst
  geoips/commandline/ancillary_info/cmd_instructions.yaml
  geoips/commandline/create_sector_image.py
  geoips/commandline/geoips_test.py
  pyproject.toml
  tests/scripts/console_script_create_sector_image.sh
  tests/unit_tests/commandline/test_geoips_test_sector.py
Labels: refactor, cli, 2024-workshop

#614 608 documentation system requirements for geoips
  docs/source/new-docs/getting-started/system-requirements/index.rst
  docs/source/releases/latest/608-documentation-system-requirements-for-geoips.yaml
  docs/source/releases/v1_13_0a0.rst
Labels: documentation, 2024-workshop

#718 495 change geoips get to geoips describe
  docs/source/releases/latest/495-change-geoips-get-to-geoips-describe.yaml
  docs/source/userguide/command_line.rst
  geoips/commandline/ancillary_info/alias_mapping.yaml
  geoips/commandline/ancillary_info/cmd_instructions.yaml
  geoips/commandline/commandline_interface.py
  geoips/commandline/geoips_command.py
  geoips/commandline/geoips_describe.py
  tests/unit_tests/commandline/test_geoips_describe_family.py
  tests/unit_tests/commandline/test_geoips_describe_interface.py
  tests/unit_tests/commandline/test_geoips_describe_package.py
  tests/unit_tests/commandline/test_geoips_describe_plugin.py
Labels: cli, 2024-workshop

#722 WORKSHOP BUG FIX Update AWS download script and abi_l2_netcdf reader
  docs/source/releases/latest/bug-fix-for-aws-download-script-and-abi_l2_netcdf-reader.yaml
  geoips/plugins/modules/readers/abi_l2_netcdf.py
  tests/download_noaa_aws.sh
Labels: bug, 2024-workshop

#724 Fix ``geoips tree`` regression for workshop
  docs/source/releases/latest/final-CLI-updates-before-workshop.yaml
  docs/source/userguide/plugin_development/algorithm.rst
  geoips/commandline/ancillary_info/alias_mapping.yaml
  geoips/commandline/geoips_describe.py
  geoips/commandline/geoips_list.py
  geoips/commandline/geoips_tree.py
Labels: regression, cli, 2024-workshop

#689 WORKSHOP BUG FIX Add xarray dict family
  docs/source/releases/latest/add_xarray_dict_family.yaml
  docs/source/releases/v1_14_0a0.rst
  geoips/create_plugin_registries.py
  geoips/interfaces/module_based/output_checkers.py
  geoips/interfaces/module_based/output_formatters.py
  geoips/plugins/modules/output_checkers/image.py
  geoips/plugins/modules/procflows/single_source.py
  geoips/schema/products/unsectored_xarray_dict_to_algorithm_to_output_format.yaml
  tests/unit_tests/commandline/test_log_setup.py
Labels: bug, 2024-workshop
