Repository NRLMMD-GEOIPS/geoips, pull requests merged in 2024-08, with the labels that each got.

#726 CLI Documentation update / CLI small bug fixes and format updates
  docs/source/releases/latest/CLI-documentation-update-for-workshop.yaml
  docs/source/userguide/command_line.rst
  geoips/commandline/commandline_interface.py
  geoips/commandline/geoips_command.py
  geoips/commandline/geoips_describe.py
  geoips/commandline/geoips_list.py
  tests/unit_tests/commandline/test_geoips_describe_interface.py
  tests/unit_tests/commandline/test_geoips_describe_plugin.py
  tests/unit_tests/commandline/test_geoips_list_packages.py
Labels: bug, refactor, cli, 2024-workshop

#732 Adding NOAA-20, NOAA-21, S-NPP AWS downloads
  Dockerfile
  docs/source/releases/latest/add_viirs_to_aws_download_script.yaml
  geoips/plugins/modules/procflows/single_source.py
  tests/download_noaa_aws.sh
Labels: testing

#746 Add brassy build workflow on new tag
  .github/workflows/new-brassy-note.yaml
  docs/source/releases/latest/738-new-branch-brassy-on-tag.yaml
Labels: actions
