Repository NRLMMD-GEOIPS/geoips, pull requests merged in 2024-03, with the labels that each got.

#403 algorithm_interpolator_colormapper interpolation bug fix
  docs/source/releases/index.rst
  docs/source/releases/v1_11_7a0.rst
  docs/source/releases/v1_12_2a0.rst
  geoips/plugins/modules/procflows/single_source.py
Labels: bug

#450 448: Remove unnecessary requirement for imagemagick
  Dockerfile
  docs/source/releases/v1_12_2a0.rst
  docs/source/starter/expert_installation.rst
  docs/source/starter/mac_installation.rst
  setup.sh
  setup/check_system_requirements.sh
Labels: bug, documentation

#417 416 replace sys argv with argparse
  docs/source/releases/v1_12_2a0.rst
  geoips/create_plugin_registries.py
Labels: refactor
