Repository NRLMMD-GEOIPS/geoips, pull requests merged in 2025-05, with the labels that each got.

#965 OBP workflow definition enhancements
  docs/dev/order_based_procflow.rst
  docs/source/releases/latest/965-obp-workflow-definition-enhancements.yaml
  geoips/plugins/modules/procflows/order_based.py
  geoips/plugins/yaml/workflows/abi.yaml
  geoips/plugins/yaml/workflows/geostationary_dmw/windbarbs_dmw_high.yaml
  geoips/plugins/yaml/workflows/geostationary_dmw/windbarbs_dmw_low.yaml
  geoips/plugins/yaml/workflows/geostationary_dmw/windbarbs_dmw_mid.yaml
  geoips/plugins/yaml/workflows/geostationary_dmw/windbarbs_dmw_multi_level.yaml
  geoips/plugins/yaml/workflows/read_test.yaml
  geoips/plugins/yaml/workflows/visir/IR-BD.yaml
  geoips/plugins/yaml/workflows/visir/Infrared-Gray.yaml
  geoips/plugins/yaml/workflows/visir/Infrared.yaml
  geoips/plugins/yaml/workflows/visir/Visible.yaml
  geoips/plugins/yaml/workflows/visir/WV-Lower.yaml
  geoips/plugins/yaml/workflows/visir/WV-Upper.yaml
  geoips/plugins/yaml/workflows/visir/WV.yaml
  geoips/plugins/yaml/workflows/visir/nasa_dust_rgb.yaml
  geoips/pydantic/bases.py
  geoips/pydantic/workflows.py
  tests/unit_tests/pydantic/bases/test_bases.py
  tests/unit_tests/pydantic/conftest.py
  tests/unit_tests/pydantic/workflows/test_reader_arguments_model.py
  tests/unit_tests/pydantic/workflows/test_workflow_step_definition_model.py
  tests/unit_tests/pydantic/workflows/test_workflow_step_model.py
  tests/unit_tests/pydantic/workflows/test_workflows.py
Labels: order based procflow

#986 Python dependency and interactive log level
  Dockerfile
  docs/source/getting-started/installing/expert.rst
  docs/source/getting-started/installing/linux_with_conda.rst
  docs/source/getting-started/installing/mac_with_conda.rst
  docs/source/releases/latest/python-dependency-and-interactive-log-level.yaml
  geoips/__init__.py
  pyproject.toml
Labels: refactor

#989 Test expose unit test fix
  docs/source/releases/latest/test-expose-unit-test-fix.yaml
  tests/unit_tests/commandline/test_expose.py
Labels: bug

#959 Introduce new type that makes handling singular and plural forms of plugins cleanly easy
  docs/source/releases/latest/946-handle-singular-and-plural-forms-of-plugins-cleanly.yaml
  geoips/utils/types/partial_lexeme.py
  tests/unit_tests/utils/types/test_partial_lexeme.py
Labels: enhancement

#816 Standardize Reader Arguments
  docs/source/releases/latest/816-standardize-reader-args.yaml
  geoips/plugins/modules/readers/abi_l2_netcdf.py
  geoips/plugins/modules/readers/ahi_hsd.py
  geoips/plugins/modules/readers/amsr2_netcdf.py
  geoips/plugins/modules/readers/ssmi_binary.py
  geoips/plugins/modules/readers/ssmis_binary.py
Labels: order based procflow

#994 507 documentation for developer assisted package creation
  docs/source/contribute/coding-standards.rst
  docs/source/contribute/dev-assisted-package-creation.rst
  docs/source/contribute/index.rst
  docs/source/releases/latest/dev-assist-package-translation.yaml
Labels: documentation

#970 PluginRegistry Class Updates
  .cspell.json
  docs/source/releases/latest/945-plugin-registry-class.yaml
  geoips/commandline/geoips_validate.py
  geoips/interfaces/base.py
  geoips/plugin_registry.py
  tests/unit_tests/plugin_registries/test_plugin_registries.py
  tests/unit_tests/plugins/test_get_plugin_metadata.py
Labels: testing, refactor

#984 Enhance YAML-based testing framework
  docs/source/releases/latest/984-enhance-yaml-based-testing.yaml
  geoips/pydantic/sectors.py
  tests/unit_tests/pydantic/sectors/test_cases.yaml
  tests/unit_tests/pydantic/sectors/test_sectors.py
  tests/unit_tests/pydantic/utils.py
Labels: enhancement, YAML-based test framework
