Repository NRLMMD-GEOIPS/geoips, pull requests merged in 2025-01, with the labels that each got.

#859 Create CODEOWNERS
  .github/CODEOWNERS
  docs/source/releases/latest/code-owners.yaml
Labels: actions

#863 Add build stable image on tag workflow
  .github/workflows/build-stable-image.yaml
  docs/source/releases/latest/build_stable_image_on_tag.yaml
Labels: actions

#864 Typo: Add packages: write and docker_token to build-stable-image.yaml
  .github/workflows/build-stable-image.yaml
Labels: actions

#876 Update pytest ini file to add GeoIPS repo root to pythonpath on pytest run
  .github/workflows/build-stable-image.yaml
  docs/source/releases/latest/pytest-add-rootdir-to-pythonpath.yaml
  pytest.ini
Labels: bug

#871 Seviri hrit bug fix
  docs/source/releases/latest/seviri_hrit-bug-fix.yaml
  geoips/plugins/modules/readers/seviri_hrit.py
Labels: bug

#861 Numpy 2.0 upgrade
  docs/source/releases/latest/861-numpy-unpin.yaml
  pyproject.toml
Labels: installation

#881 Get Plugin Metadata
  docs/source/releases/latest/create-get-plugin-metadata.yaml
  geoips/interfaces/base.py
  geoips/interfaces/yaml_based/products.py
  tests/unit_tests/commandline/cli_top_level_tester.py
  tests/unit_tests/plugins/test_get_plugin_metadata.py
Labels: enhancement

#784 Standardize amsr2 reader naming convention across the file
  docs/source/releases/latest/documentation-AMSR2_NetCDF_reader.yaml
  geoips/plugins/modules/readers/amsr2_netcdf.py
Labels: refactor

#882 Fix cygnss unit test xfail behaviour
  docs/source/releases/latest/873-cygnss-netcdf-unit-test-failing.yaml
  geoips/plugins/modules/readers/cygnss_netcdf.py
  tests/unit_tests_long/plugins/modules/readers/test_readers.py
Labels: bug
