Repository NRLMMD-GEOIPS/geoips, pull requests merged in 2025-06, with the labels that each got.

#980 Alphabetize arguments in help output
  docs/build_docs.py
  docs/source/concepts/architecture/command_line_interface.rst
  docs/source/concepts/architecture/index.rst
  docs/source/releases/latest/711-positional-arguments-should-be-alphabetized-in-help-output.yaml
  geoips/commandline/geoips_command.py
  tests/unit_tests/commandline/test_get_commandline_instructions.py
  tests/unit_tests/commandline/test_help_sorting.py
Labels: enhancement

#727 Copy edit CLI docs
  .cspell.json
  docs/source/concepts/functionality/command-line/command_line_autodoc.rst
  docs/source/concepts/functionality/command-line/index.rst
  docs/source/concepts/functionality/data_units.rst
  docs/source/new-docs/concepts/functionality/interfaces/module_based/algorithm.rst
  docs/source/releases/latest/copy-edit-cli-docs.yaml
Labels: documentation, 2024-workshop

#1074 Nextcloud test dataset updates
  .cspell.json
  docs/source/releases/latest/nextcloud-test-dataset-updates.yaml
  geoips/commandline/geoips_config.py
  setup/test-data-urls.yaml
  tests/integration_tests/test_integration.py
  tests/outputs/cygnss.tc.windspeed.imagery_clean/20240125_060307_SH062024_cygnss_cygnss_windspeed_80kts_6p22_1p0-clean.png
Labels: testing

#1035 1034 add documentation about test sectors
  .cspell.json
  docs/source/concepts/architecture/tests/index.rst
  docs/source/concepts/architecture/tests/test-sectors.rst
  docs/source/releases/latest/1034-add-documentation-about-test-sectors.yaml
Labels: documentation

#1001 Add support for good and neutral tests in YAML-based testing
  docs/source/releases/latest/1001-add-support-for-neutral-tests-in-yaml-based-testing.yaml
  tests/unit_tests/pydantic/feature_annotators/test_cases_bad.yaml
  tests/unit_tests/pydantic/feature_annotators/test_cases_neutral.yaml
  tests/unit_tests/pydantic/feature_annotators/test_feature_annotators.py
  tests/unit_tests/pydantic/sectors/test_cases_bad.yaml
  tests/unit_tests/pydantic/sectors/test_cases_neutral.yaml
  tests/unit_tests/pydantic/sectors/test_sectors.py
  tests/unit_tests/pydantic/utils.py
Labels: feature, YAML-based test framework

#1038 1036 update npfromstring to npfrombuffer
  docs/source/releases/latest/1036-update-npfromstring-to-npfrombuffer.yaml
  geoips/plugins/modules/readers/ahi_hsd.py
  geoips/plugins/modules/readers/ssmis_binary.py
Labels: bug

#1079 AMSU-B Test Dataset URL
  docs/source/releases/latest/amsub-test-dataset-url.yaml
  geoips/commandline/ancillary_info/test-data-urls.yaml
  setup/test-data-urls.yaml
  tests/integration_tests/test_integration.py
Labels: testing

#1027 ``geoips run obp`` command
  docs/source/releases/latest/geoips-run-obp.yaml
  geoips/commandline/ancillary_info/alias_mapping.yaml
  geoips/commandline/ancillary_info/cmd_instructions.yaml
  geoips/commandline/commandline_interface.py
  geoips/commandline/geoips_command.py
  geoips/commandline/geoips_run.py
  tests/unit_tests/commandline/test_geoips_run.py
Labels: cli, order based procflow

#1049 1048 add documentation on how to run tests
  .cspell.json
  docs/dev/integration_tests.rst
  docs/source/contribute/index.rst
  docs/source/contribute/testing/index.rst
  docs/source/contribute/testing/running_tests.rst
  docs/source/releases/latest/1048-add-documentation-on-how-to-run-tests.yaml
Labels: documentation
