Repository NRLMMD-GEOIPS/geoips, pull requests merged in 2025-03, with the labels that each got.

#858 Integrate test all into pytest tests
  docs/dev/integration_tests.rst
  docs/source/releases/latest/834-move-all-integration-tests-to-pytests.yaml
  docs/source/releases/latest/integrate-test-all-into-pytest-tests.yaml
  pytest.ini
  tests/integration_tests/test_integration.py
  tests/test_all.sh
Labels: testing

#908 Fix Installation Issues
  README.md
  docs/source/getting-started/installing/linux_with_conda.rst
  docs/source/releases/latest/905-geoips-installation-fix.yaml
Labels: documentation

#916 Add Conceptual Interface Documentation
  docs/source/concepts/functionality/index.rst
  docs/source/concepts/functionality/interfaces/index.rst
  docs/source/concepts/functionality/interfaces/module_based/algorithm.rst
  docs/source/concepts/functionality/interfaces/module_based/colormapper.rst
  docs/source/concepts/functionality/interfaces/module_based/filename_formats.rst
  docs/source/concepts/functionality/interfaces/module_based/interpolators.rst
  docs/source/concepts/functionality/interfaces/module_based/output_formats.rst
  docs/source/concepts/functionality/interfaces/module_based/procflows.rst
  docs/source/concepts/functionality/interfaces/module_based/readers.rst
  docs/source/concepts/functionality/interfaces/module_based/title_formats.rst
  docs/source/concepts/functionality/interfaces/yaml_based/dynamic_sectors.rst
  docs/source/concepts/functionality/interfaces/yaml_based/feature_annotators.rst
  docs/source/concepts/functionality/interfaces/yaml_based/gridline_annotators.rst
  docs/source/concepts/functionality/interfaces/yaml_based/product_defaults.rst
  docs/source/concepts/functionality/interfaces/yaml_based/products.rst
  docs/source/concepts/functionality/interfaces/yaml_based/static_sectors.rst
  docs/source/releases/latest/915-add-conceptual-interface-documentation.yaml
Labels: documentation

#920 Update base_paths.py with default outdir
  docs/source/releases/latest/make-geoips-pipable.yaml
  geoips/filenames/base_paths.py
Labels: enhancement

#922 Commandline Fix for Multi-Document YAML Files
  docs/source/releases/latest/unit-test-fix-for-multi-doc-yaml-plugins.yaml
  geoips/commandline/ancillary_info/cmd_instructions.yaml
  geoips/commandline/geoips_validate.py
  tests/unit_tests/commandline/test_geoips_validate.py
Labels: bug

#899 ``fci_netcdf`` GeoColor Update
  docs/source/releases/latest/fci-reader-geocolor-update.yaml
  geoips/plugins/modules/readers/fci_netcdf.py
Labels: enhancement, refactor
