Repository NRLMMD-GEOIPS/geoips, pull requests merged in 2025-02, with the labels that each got.

#763 New Product Family unsectored_xarray_dict_to_algorithm_to_output_format
  docs/source/releases/latest/new-prd-fam-unsectored-xarray-dict-to-algorithm-to-output-format.yaml
  geoips/commandline/ancillary_info/test_data.py
  geoips/plugins/modules/output_formatters/unprojected_image.py
  geoips/plugins/modules/procflows/single_source.py
  geoips/plugins/yaml/products/seviri.yaml
  geoips/schema/product_defaults/unsectored_xarray_dict_to_algorithm_to_output_format.yaml
  setup/test-data-urls.yaml
  tests/integration_tests/full_install.sh
  tests/integration_tests/test_integration.py
  tests/outputs/seviri.WV-Upper.no_self_register.unprojected_image/20231211.080000.msg-2.seviri.WV-Upper-No-SR.unk.nesdisstar..png
  tests/scripts/seviri.WV-Upper.no_self_register.unprojected_image.sh
Labels: enhancement, procflows

#767 Add basic nrtp tutorial
  docs/source/releases/latest/766-add-basic-nrtp-example-to-docs.yaml
  docs/source/tutorials/extending-with-plugins/algorithm.rst
  docs/source/tutorials/extending-with-plugins/colormapper/colorful_cloud_height.png
  docs/source/tutorials/extending-with-plugins/colormapper/index.rst
  docs/source/tutorials/extending-with-plugins/feature_annotator/index.rst
  docs/source/tutorials/extending-with-plugins/feature_annotator/my_feature_gridline.png
  docs/source/tutorials/extending-with-plugins/gridline_annotator.rst
  docs/source/tutorials/extending-with-plugins/index.rst
  docs/source/tutorials/extending-with-plugins/output_formatter.rst
  docs/source/tutorials/extending-with-plugins/product/index.rst
  docs/source/tutorials/extending-with-plugins/product/my_cloud_depth.png
  docs/source/tutorials/extending-with-plugins/product/my_cloud_top_height.png
  docs/source/tutorials/extending-with-plugins/product_default.rst
  docs/source/tutorials/extending-with-plugins/reader.rst
  docs/source/tutorials/extending-with-plugins/static_sector/index.rst
  docs/source/tutorials/extending-with-plugins/static_sector/my_conus_sector.png
  docs/source/tutorials/extending-with-plugins/static_sector/my_conus_sector_cth.png
  docs/source/tutorials/index.rst
  docs/source/tutorials/nrtp-examples/index.rst
  docs/source/tutorials/nrtp-examples/using-inotifywait-for-basic-near-real-time-processing.rst
Labels: documentation

#781 Automate ``create_plugin_registries``
  docs/source/concepts/functionality/plugin-registries.rst
  docs/source/releases/latest/automate-create-plugin-registries.yaml
  geoips/commandline/args.py
  geoips/commandline/geoips_run.py
  geoips/commandline/geoips_test.py
  geoips/filenames/base_paths.py
  geoips/interfaces/base.py
  geoips/interfaces/module_based/output_checkers.py
  geoips/interfaces/yaml_based/products.py
  tests/unit_tests/plugins/test_get_plugin.py
Labels: Dev Update, refactor

#902 Non editable unit test fix
  docs/source/releases/latest/non-editable-unit-test-fix.yaml
  tests/unit_tests/commandline/cli_top_level_tester.py
  tests/unit_tests/commandline/test_geoips_list_scripts.py
Labels: bug
